#!/usr/bin/env bash
set -euo pipefail

# Install aura if not installed
if ! pacman -Qq aura-bin &> /dev/null; then
    echo "Installing AUR..."
    cd /tmp
    git clone https://aur.archlinux.org/aura-bin.git
    cd aura-bin
    makepkg -si --noconfirm
    cd ~
    # Clean up the build directory
    rm -rf /tmp/aura-bin
fi

# Install AUR packages
echo "Installing AUR Packages..."
git clone https://aur.archlinux.org/einfach-grub-theme.git
cd einfach-grub-theme
makepkg -si
cd
aura -A --noconfirm brave-origin-bin kanata-bin pcloud-drive \
einfach-icon-theme



# Fnm install (Currently Commmented)
# curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
