#!/usr/bin/env bash
set -euo pipefail


# AUR install
cd /tmp
git clone https://aur.archlinux.org/aura-bin.git
cd aura-bin
makepkg -si --noconfirm
cd ~
# Clean up the build directory
rm -rf /tmp/aura-bin


# AUR packages
aura -A --noconfirm brave-origin-bin kanata-bin pcloud-drive \
ttf-noto-emoji-monochrome einfach-icon-theme einfach-grub-theme


# Fnm install (Currently Commmented)
# curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
