#!/usr/bin/env bash

set -e

echo "Select an option:"
echo "1) Arch Base Install"
echo "2) Setup Arch Packages"
echo "3) Setup Arch Aur and Services"
echo "4) Exit"

read -rp "Enter your choice [1-4]: " choice

case "$choice" in
    1)
        echo "Installing Arch..."
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/arch-installation/main/base)
        ;;
    2)
        echo "Setting up Arch Packages"
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/arch-installation/main/packages)
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/arch-installation/main/import-dotfiles)
        ;;
    3)
        echo "Setting up Aur & Services"
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/arch-installation/main/aur-packages)
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/arch-installation/main/services)
        ;;
    4)
        echo "Exiting."
        exit 0
        ;;
    *)
        echo "Invalid choice."
        exit 1
        ;;
esac
