#!/usr/bin/env bash

set -e

echo "Select an option:"
echo "1) Arch Clean Install"
echo "2) Setup Arch for Personal Use"
echo "3) Setup Arch for Work"
echo "4) Exit"

read -rp "Enter your choice [1-4]: " choice

case "$choice" in
    1)
        echo "Installing Arch..."
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/arch-installation/main/script)
        ;;
    2)
        echo "Setting up Arch for Personal Use..."
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/packages/main/personal)
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/dotfiles-import/main/personal)
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/configuration/main/configure)
        ;;
    3)
        echo "Setting up Arch for Work..."
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/packages/main/work)
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/dotfiles-import/main/work)
        sh <(curl -Lks raw.githubusercontent.com/DerJimno/configuration/main/configure)
        ;;
    4)
        echo "Exiting."
        exit 0
        ;;
    *)
        echo "Invalid choice."
        exit 1
        ;;
esac
